{% set name = "jupyterlab-niryo-one" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_niryo_one-{{ version }}.tar.gz
  sha256: 312fe3722fcceadb9ba2419087178d8de5223abb0c2c04bd2bfd49969482f772

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - jupyter_packaging
    - pip
    - python {{ python_min }}
  run:
    - jupyterlab-blockly >=0.1.0a5,<0.2
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_niryo_one
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quantstack/jupyterlab-niryo-one
  summary: Blockly extension for JupyterLab to control the Niryo One robot.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - hbcarlos
